name: Deploy to EC2

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        
        # The commands to run on your server
        script: |
          cd ~/Geometry-Wars-KW-Server
          git pull
          docker-compose down
          docker-compose up -d --build
          docker image prune -f